---
spring:
  application.name: sample-boot-micro
  messages.basename: messages-validation, messages
  banner.location: banner.txt
  cache.jcache.config: classpath:ehcache.xml
  jackson.serialization:
      indent-output: true
  servlet.multipart:
    max-file-size: 20MB
    max-request-size: 20MB
  jpa.open-in-view: false

logging.config: classpath:logback-spring.xml

server:
  port: 8080
  error:
    whitelabel.enabled: false
    path: /api/error

management:
  endpoints.web:
    base-path: /management
    exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

extension:
  security.auth.enabled: false
  datasource:
    default:
      url: jdbc:h2:tcp://localhost:9092/mem:testdb
      username: sa
      password:
      jpa:
        package-to-scan: sample.model
        show-sql: false
        hibernate.ddl-auto: none
    system:
      url: jdbc:h2:tcp://localhost:9092/mem:system
      username: sa
      password:
      jpa:
        package-to-scan: sample.context
        show-sql: false
        hibernate.ddl-auto: none

---
spring:
  profiles: production

extension:
  datasource:
    default:
      url: jdbc:oracle:thin:@xxx.xxx.xxx.xxx:1521:xx
      username: XXXXXX
      password: XXXXXX
    system:
      url: jdbc:oracle:thin:@xxx.xxx.xxx.xxx:1521:xx
      username: XXXXXX
      password: XXXXXX
